[versions]
agp = "8.1.0"
coil-compose = "2.3.0"
datastore-preferences = "1.0.0"
kotlinx-serialization-json = "1.5.1"
kotlinx-coroutines-android = "1.6.4"
kotlinx-metadata-jvm = "0.6.0"
navigation-compose = "2.6.0"
kotlin-version = "1.8.10"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
hilt-android = "2.47"
hilt-version = "2.44"
play-services-auth = "20.6.0"
retrofit = "2.9.0"
okhttp-urlconnection = "5.0.0-alpha.11"
logging-interceptor = "5.0.0-alpha.11"
kotlin-serialization-converter = "0.8.0"

[libraries]
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadata-jvm" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name= "okhttp-urlconnection", version.ref = "okhttp-urlconnection" }
logging-interceptor = { group = "com.squareup.okhttp3", name= "logging-interceptor", version.ref = "logging-interceptor" }
play-services-auth = { group = "com.google.android.gms", name= "play-services-auth", version.ref = "play-services-auth" }
retrofit = { group = "com.squareup.retrofit2", name= "retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlin-serialization-converter" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version"}
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-version"}

[bundles]

